apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: gcd-deployment
  labels:
    app: appgcd
spec:
  selector:
    matchLabels:
      app: appgcd
  replicas: 1
  template:
    metadata:
      labels:
        app: appgcd
    spec:
      containers:
      - name: appgcd
        image: local/gcd
        imagePullPolicy: Never
        ports:
        - name: gcd-service
          containerPort: 3001

---
apiVersion: v1
kind: Service
metadata:
  name: gcd-service
spec:
  selector:
    app: appgcd
  ports:
  - port: 3001
    targetPort: gcd-service